# Generated by Django 2.2.2 on 2019-08-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=30)),
                ('company_alias', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='')),
                ('Originator', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('trade_licence', models.FileField(default=None, upload_to='')),
            ],
        ),
    ]
