# Generated by Django 2.2.2 on 2019-07-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
