# Generated by Django 2.2.2 on 2019-07-30 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20190713_0934'),
        ('Accounts', '0002_auto_20190711_1411'),
    ]

    operations = [
    ]
