# Generated by Django 2.2.2 on 2019-07-31 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_merge_20190730_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='activate',
        ),
    ]
